# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-14 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('information', models.TextField()),
                ('IP', models.TextField()),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mysql',
            fields=[
                ('information', models.TextField()),
                ('IP', models.TextField()),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
